[package]
name = "video_player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27.5"
pollster = "0.2"
xme_engine = { path = "../../xme_engine" }
